server:
  port: 8080


spring:
  application:
    name: BaseinfoProvider
  profiles:
    include:
    - pageinfo
    - mybatis
    - eureka
    - datasource
    - common
    - sso
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
