server:
  port: 8090


spring:
  application:
    name: ExclusiveDoctorProvider
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: false #不要为我们工程中的资源文件建立映射
  profiles:
    include:
     - sso
     - mybatis
     - eureka
     - common
     - datasource
     - pageinfo