server:
  port: 8090


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://10.0.0.12:5555/eureka/,http://10.0.0.12:7777/eureka/
spring:
  datasource:
        name: sso
        url: jdbc:mysql:///UserManager?characterEncoding=utf8&useSSL=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        dbcp2:
              min-idle: 5   #最小维持的连接数
              initial-size: 5  #初始化的连接数
              max-total: 5 #最大的连接数
              max-wait-millis: 200 #对大等待时间
  application:
    name: ExclusiveDoctorProvider
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: false #不要为我们工程中的资源文件建立映射

mybatis:
  config-location: classpath:mybatis.xml  #mybatis配置文件路径
  type-aliases-package: com.cqjtu.domain
  mapper-locations:
  - classpath:mapper/*.xml