

server:
  port: 8082




spring:
    application:
      name: HospitalProvider
    mvc:
      throw-exception-if-no-handler-found: true #当出现404的时候直接抛出异常
    resources:
      add-mappings: false
    profiles:
      include:
      - datasource
      - mybatis
      - eureka
      - sso
      - pageinfo
      - common


sendTokenToAdminMail:
  adminMail: 799243917@qq.com
  keepTime: 6000000 #毫秒 6000秒
  sendMail: 1727078617@qq.com
  sendPass: ryjculxdnrwmcbba
  smtpServer: smtp.qq.com


HospitalAdmin:
  code: 3 #标识医院管理员的用户类别编码

