

spring:
  application:
    name: ApiGateway


server:
  port: 8089
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://10.0.0.12:5555/eureka/,http://10.0.0.12:7777/eureka/


zuul:
  add-host-header: true















