server:
  port: 8090



spring:
  cloud:
    inetutils:
      preferred-networks:
       - 10.0
  application:
    name: FeedbackPlatformProvider
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: false
  profiles:
    include:
    - sso
    - eureka
    - mybatis
    - datasource
    - pageinfo