

server:
  port: 8081



spring:
    application:
      name: AppointmentProvider
    mvc:
      throw-exception-if-no-handler-found: true #当出现404的时候直接抛出异常
    resources:
      add-mappings: false
    profiles:
      include:
        - mybatis
        - eureka
        - datasource
        - common
        - sso




eureka:
  client:
    fetch-registry: true
    serviceUrl:
          defaultZone: http://10.0.0.101:5555/eureka/,http://10.0.0.101:7777/eureka/