server:
  port: 4321

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 2Mb
      max-request-size: 20Mb
      file-size-threshold: 10Mb
  mvc:
    static-path-pattern: /files/**
    throw-exception-if-no-handler-found: true
  resources:
        add-mappings: true
        static-locations: file:/home/zjh/profiles #file:/Users/zjhfyq/Dev/Ftp/
  profiles:
    include:
    - sso
    - eureka
    - datasource
    - mybatis
  application:
      name: FileProvider





smartHospital:
  filePath: /home/zjh/profiles #/Users/zjhfyq/Dev/Ftp/





picture:
  format: bmp,jpg,png

