server:
  port: 4321

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 2Mb
      max-request-size: 20Mb
      file-size-threshold: 10Mb
  mvc:
    static-path-pattern: /files/**
    throw-exception-if-no-handler-found: true
  resources:
        add-mappings: true
        static-locations: file:/Users/zjhfyq/Dev/Ftp/
  profiles:
    include:
    - sso
    - eureka
    - datesource
    - mybatis



smartHospital:
  filePath: /Users/zjhfyq/Dev/Ftp/





picture:
  format: bmp,jpg,png

