server:
  port: 4321

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 2Mb
      max-request-size: 20Mb
      file-size-threshold: 10Mb
  mvc:
    static-path-pattern: /files/**
    throw-exception-if-no-handler-found: true
  resources:
        add-mappings: true
        static-locations: file:/Users/zjhfyq/Dev/Ftp/



smartHospital:
  filePath: /Users/zjhfyq/Dev/Ftp/



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
          defaultZone: http://10.0.0.12:5555/eureka/,http://10.0.0.12:7777/eureka/