SSOServer:
  loginAddress: http://api.zjhfyq.cn/api-sso/login
  validateAddress: http://api.zjhfyq.cn/api-sso/validate
  logoutAddress: http://api.zjhfyq.cn/api-sso/signout

  loginService: http://SSOSERVERPROVIDER/login
  validateService: http://SSOSERVERPROVIDER/validate
  logoutService: http://SSOSERVERPROVIDER/signout
