spring:
  datasource:
        name: sso
        url: jdbc:mysql://10.0.0.13:3306/smarthospital_test?characterEncoding=utf8&useSSL=true
        username: zct
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        dbcp2:
              min-idle: 5   #最小维持的连接数
              initial-size: 5  #初始化的连接数
              max-total: 5 #最大的连接数
              max-wait-millis: 200 #对大等待时间