eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://10.0.0.101:5555/eureka/,http://10.0.0.101:7777/eureka/ #http://10.0.0.8:8888/eureka/
