
server:
  port: 5555



eureka:
  server:
    enable-self-preservation: false #eureka的自我保护


  instance:
    hostname: eureka-server-two
  client:
    fetch-registry: false
    register-with-eureka: true  #false是不自己注册到自己，如果eureka有多个以后，就设置为true
    serviceUrl:
          defaultZone: http://127.0.0.1:7777/eureka/
spring:
  application:
    name: smart-hospital-eureka-server-two
  cloud:
      inetutils:
        preferred-networks:
         - 10.0


