
server:
  port: 7777

spring:
  application:
    name: smart-hospital-eureka-server-one
  cloud:
      inetutils:
        preferred-networks:
         - 10.0
eureka:
  server:
    enable-self-preservation: false #eureka的自我保护

  instance:
    hostname: eureka-server-one
    prefer-ip-address: true


  client:
    fetch-registry: false
    register-with-eureka: true  #false是不自己注册到自己
    serviceUrl:
          defaultZone: http://10.0.0.101:5555/eureka/


