server:
  port: 8083


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
spring:
  application:
    name: ValidateProvider
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: false #不要为我们工程中的资源文件建立映射


mail:
  mailUsername: 799243917@qq.com
  mailPassword:
  smtpServer: smtp.qq.com
